# 总开关
enabled: true

# 死亡后给予的药水效果
potion-effect:
  # 可以在这里添加上你要的药水效果，大小写都可以，不给药水效果的话不要留空，改成type: []
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
  type:
    - BLINDNESS
    - NAUSEA
  # 药水持续时间
  time: 30
  # 药水等级（游戏里的药水等级是这个等级+1）
  level: 1

# 提示标题，随机选一个
title:
  - "死亡之神对你感到失望！"

# 提示副标题，随机选一个
subtitle:
  - "腐竹对你降下了神罚~"

# 是否保留饱食度，为true的时候保留死亡之前的饱食度
keep-food-level: true

